### PR TITLE
added functions to check if bot has been addressed in message and str…

### PR DESCRIPTION
**Pull request by CiaranHannigan**
…ipping all instances of the bots name from the string. ES6: switched var to let in all instances in util.js

### CODE REVIEW

**Comment by CiaranHannigan** [comment]
This is part of https://github.com/ibm-cloud-solutions/hubot-ibmcloud-nlc/issues/62

**Comment by nsand** [comment]
`utils.test.js` has an issue in `test confirmed response 'no'` where message = 'hubot no' succeeds because it's undefined and the test actually ends. If you add `let` in front, suddenly the test fails.

**Comment by CiaranHannigan** [comment]
Found the problem with that issue @nsand 

```
.then(() => {}, () => {
    done();
});
```

The first callback is for onFulfilled.

**Comment by aeweidne** [comment]
+1

**Pull request merged**
